stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tarcinapp/entity-persistence-gateway:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_MTU: "1450"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: '#rancher-pipeline-test'
    notifier: c-v4f4b:n-vtgsh
  condition:
  - Success
  - Changed
  - Failed
