app:
  auth:
    providers: []
#      - issuer: "https://securetoken.google.com/proje-id"
#        jwk-set-uri: "https://www.googleapis.com/service_accounts/v1/jwk/..."
#        clockSkewSeconds: 60
#        
#      - issuer: "tarcinapp-internal"
#        public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA..."
#        clockSkewSeconds: 10