app:
  queries:
    my: "'set[owners][userIds]='+#userId"
    actives: "'set[actives]'"
    inactives: "'set[inactives]'"
    name: "'filter[where][_name]=' + #query['name']"
    slug: "'filter[where][_slug]=' + #query['slug']"
