app:
  rs256PublicKey: your-key-from-k8s-secret #Override this field with a value from Kubernetes secret. See .README.
  requestHeaders:
    authenticationSubject: "TarcinappAuthSubject"
    requestId: "TarcinappRequestId"
  requestIdPrefix: "TAPP"
  backend:
    protocol: http
    host: entity-persistence-service
    port: 80
spring:
  application: 
    name: entity-persistence-gateway
  redis: 
    host: gateway-redis-master
    port: 6379
    database: 0
    password: your-password-from-k8s-secret #Override this field with a value from Kubernetes secret. See .README.
  cloud:
    gateway:
      routes:
      - id: createEntity
        uri: ${app.backend.protocol}://${app.backend.host}:${app.backend.port}/generic-entities
        predicates:
        - Path=/generic-entities
        - Method=POST
        filters:
        - name: RequestSize
          args:
            maxSize: 1MB
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
        - name: SetOwnerUsersToRequest
      - id: updateAllEntities
        uri: ${app.backend.protocol}://${app.backend.host}:${app.backend.port}/generic-entities
        predicates:
        - Path=/generic-entities
        - Method=PATCH
        filters:
        - name: RequestSize
          args:
            maxSize: 1MB
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
      - id: findEntities
        uri: ${app.backend.protocol}://${app.backend.host}:${app.backend.port}/generic-entities
        predicates:
        - Path=/generic-entities
        - Method=GET
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
      - id: countEntities
        uri: ${app.backend.protocol}://${app.backend.host}:${app.backend.port}/generic-entities/count
        predicates:
        - Path=/generic-entities/count
        - Method=GET
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
      - id: explorer
        uri: no://op
        predicates:
        - Path=/explorer
        filters:
        - name: SetStatus
          args:
            status: 404
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO