app:

  # set the name of your application (e.g. books, recipes, movies, etc..)
  name: entity-persistence-gateway

  # shortcode is going to be used for:
  # - prefix for generated request id for each request
  # - prefix for the role names (e.g. tarcinapp.member)
  # - jmx domain name, if jmx is enabled
  shortcode: "tarcinapp"
  debug: false
  jmx: false

  # Custom request ID header name used in logging and tracing
  requestId: "X-Request-Id"
    
  commonBaseSchema: '{"$schema":"http://json-schema.org/draft-07/schema#","type":"object","properties":{"_kind":{"type":"string"},"_slug":{"type":"string"},"_createdDateTime":{"type":"string","format":"date-time"},"_lastUpdatedDateTime":{"type":"string","format":"date-time"},"_validFromDateTime":{"type":"string","format":"date-time","nullable":true},"_validUntilDateTime":{"type":"string","format":"date-time","nullable":true},"_visibility":{"type":"string","enum":["public","protected","private"]},"_version":{"type":"number"},"_lastUpdatedBy":{"type":"string"},"_createdBy":{"type":"string"},"_ownerUsers":{"type":"array","items":{"type":"string"}},"_ownerGroups":{"type":"array","items":{"type":"string"}},"_viewerUsers":{"type":"array","items":{"type":"string"}},"_viewerGroups":{"type":"array","items":{"type":"string"}}},"required":[]}'
  
  inbound:
    address: 0.0.0.0
    port: 8081
    baseUri: /api/v1/
    metricsEnabled: true
    controllerPaths:
      entities: entities
      lists: lists
      relations: relations
      explorer: explorer
    cors:
      allowedOrigins: "http://localhost:8080"
      allowedMethods: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
      allowedHeaders: "Accept, Authorization, Cache-Control, Connection, Content-Type, Host, Origin, Referer, User-Agent, Vary, X-Geolocation, X-Requested-With"
      exposedHeaders: "Location, Content-Type"
      allowCredentials: true
      maxAge: 3600
  caching:
    enabled: true
    timeToLive: 6h
    size: 50MB
  backend:
    protocol: http
    host: entity-persistence-service
    port: 80
    baseUri: '/'
    connectTimeoutMs: 2000
    responseTimeout: 5s
  opa:
    protocol: https
    host: entity-persistence-gateway-policies
    port: 443
    connectTimeoutMs: 500
    readTimeoutMs: 300
    writeTimeoutMs: 300
    responseTimeout: 500ms  

  metricsEndpointsMap:
    "true": gateway,health,metrics
    "false": ""
---
debug: ${app.debug}
server:
  port: ${app.inbound.port}
  address: ${app.inbound.address}
  compression:
    enabled: true
    mime-types: application/json
---
spring:
  config:
    import:
      - classpath:application-routes.yml
      - classpath:application-auth.yml
      - classpath:application-logging.yml
      - classpath:application-fieldsets.yml
      - classpath:application-queries.yml
      - classpath:application-request-sizes.yml
      - classpath:application-rate-limits.yml
      - classpath:application-locks.yml
      - classpath:application-route-toggles.yml
  application:
    name: ${app.name}
  data:
    redis:
      host: gateway-redis-master
      port: 6379
      database: 0
      password: your-password-from-k8s-secret #Override this field with a value from Kubernetes secret. See .README.
  cloud:
    gateway:
      httpclient:
        connect-timeout: ${app.backend.connectTimeoutMs}
        response-timeout: ${app.backend.responseTimeout}
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${app.inbound.cors.allowedOrigins}
            allowedMethods: ${app.inbound.cors.allowedMethods}
            allowedHeaders: ${app.inbound.cors.allowedHeaders}
            exposedHeaders: ${app.inbound.cors.exposedHeaders}
            allowCredentials: ${app.inbound.cors.allowCredentials}
            maxAge: ${app.inbound.cors.maxAge}
      metrics:
        enabled: ${app.inbound.metricsEnabled}
      filter:
        local-response-cache:
          enabled: ${app.caching.enabled}
          size: ${app.caching.size}
          time-to-live: ${app.caching.timeToLive}