app:
  queries:
    my: "'sets[owners][userIds]='+#userId"
    actives: "'sets[actives]'"
    inactives: "'sets[inactives]'"
    name: "'filter[where][_name]=' + #query['name']"
    slug: "'filter[where][_slug]=' + #query['slug']"
