apiVersion: v1
kind: Secret
metadata:
  name: entity-persistence-gateway-secret
  namespace: tarcinapp-test
data:
  app.jwtsPrivateKey: "your-jwts-private-key-here"
  spring.redis.password: "your-redis-password-here"