package com.tarcinapp.entitypersistencegateway.services;

import com.tarcinapp.entitypersistencegateway.GatewaySecurityContext;
import com.tarcinapp.entitypersistencegateway.filters.common.request.GenerateRequestId;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.RandomStringUtils;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ServerWebExchange;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 * Service that centralizes the logic for Request ID generation and resolution.
 * Used by both filters and the error handler (GlobalErrorExceptionHandler).
 */
@Service
@Slf4j
public class RequestIdService {

    @Value("${app.shortcode}")
    private String requestIdPrefix;

    /**
     * Returns an existing Request ID if available, otherwise generates a new one.
     * Generated ID format: {PREFIX}-{AZP}-{TIMESTAMP}-{RANDOM}
     */
    public String resolveOrCreateId(ServerWebExchange exchange) {
        // 1. First check if it exists in exchange attributes (might have been generated by a filter)
        String existingId = exchange.getAttribute(GenerateRequestId.REQUEST_ID_ATTR);
        if (existingId != null) {
            return existingId;
        }

        // 2. Otherwise generate a new one (format-compliant fallback)
        return generateNewId(exchange);
    }

    /**
     * Generates a completely new Request ID.
     */
    public String generateNewId(ServerWebExchange exchange) {
        StringBuilder sb = new StringBuilder();

        // Date part (yyyyMMddHHmmssSSS)
        Date date = Calendar.getInstance().getTime();
        DateFormat dateFormat = new SimpleDateFormat("yyyyMMddHHmmssSSS");
        String datePart = dateFormat.format(date);

        // Detection of Auth Party (azp) via Security Context
        GatewaySecurityContext gc = exchange.getAttribute(GatewaySecurityContext.GATEWAY_SECURITY_CONTEXT_ATTR);
        String authParty = (gc != null && gc.getAuthParty() != null) ? gc.getAuthParty() : "UNKNOWN";

        // Random part (5 characters)
        String random = RandomStringUtils.secure().nextAlphanumeric(5);

        // Concatenation: PREFIX-AZP-TIMESTAMP-RANDOM
        sb.append(requestIdPrefix.toUpperCase())
          .append("-")
          .append(authParty.toUpperCase())
          .append("-")
          .append(datePart)
          .append("-")
          .append(random.toUpperCase());

        return sb.toString();
    }
}